language: swift
osx_image: xcode10
script:
  - xcodebuild -scheme "InstantMock iOS" -workspace InstantMock.xcworkspace/ -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'InstantMock'
